name: Deploy Angular to GitHub Pages
on:
  push:
    branches: [ main ]   # ou master
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - run: npm ci
      - run: npm run build -- --configuration production --base-href "/<repo>/" --deploy-url "/<repo>/"
      - run: cp dist/<APP_NAME>/browser/index.html dist/<APP_NAME>/browser/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/<APP_NAME>/browser
